# Generated by Django 2.2.10 on 2020-06-14 19:28

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[170, 162], upload_to='images')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='বাঙলার জমিদার', max_length=150)),
                ('category', models.CharField(help_text='প্রবন্ধ, গবেষণা ও অন্যান্য', max_length=150)),
                ('subcategory', models.CharField(blank=True, help_text='প্রবন্ধ', max_length=150, null=True)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='প্রবন্ধ-গবেষণা-অন্যান্য', null=True)),
                ('cover_photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[178, 121], upload_to='images')),
                ('book_details', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Publication')),
            ],
        ),
    ]
