# Generated by Django 2.2.10 on 2020-06-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='category',
            field=models.ForeignKey(help_text='প্রবন্ধ, গবেষণা ও অন্যান্য', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='bookshop.Category'),
        ),
    ]
