# Generated by Django 2.2.10 on 2020-06-16 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_auto_20200616_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='edition',
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('edition', models.CharField(blank=True, max_length=120, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Bookstore')),
            ],
        ),
    ]
