# Generated by Django 2.2.10 on 2020-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_auto_20200616_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='price',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=9),
            preserve_default=False,
        ),
    ]
