# Generated by Django 2.2.10 on 2020-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_bookstore_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
