# Generated by Django 2.2.10 on 2020-06-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0007_auto_20200617_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
