# Generated by Django 2.2.10 on 2020-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_auto_20200620_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='myslug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='slug',
            field=models.SlugField(blank=True, default='myslug', help_text='প্রবন্ধ-গবেষণা-অন্যান্য'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='myslug'),
            preserve_default=False,
        ),
    ]
