# Generated by Django 2.2.10 on 2020-06-21 18:18

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_auto_20200621_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSlugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', slugger.fields.AutoSlugField(populate_from='title')),
            ],
        ),
    ]
