# Generated by Django 2.2.10 on 2020-06-22 21:02

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_autoslugmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[178, 121], upload_to='images')),
            ],
        ),
    ]
