# Generated by Django 2.2.10 on 2020-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0013_auto_20200704_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
