# Generated by Django 2.2.10 on 2020-07-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0015_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='quantity',
        ),
    ]
