# Generated by Django 2.2.10 on 2020-07-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0016_remove_bookstore_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bookstores',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='bookstore',
            new_name='book',
        ),
    ]
