# Generated by Django 2.2.10 on 2020-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0018_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
