# Generated by Django 2.2.10 on 2020-07-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0019_billingaddress_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
