# Generated by Django 2.2.10 on 2020-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0023_remove_billingaddress_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='total_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
