# Generated by Django 2.2.10 on 2020-07-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0025_auto_20200711_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
