# Generated by Django 2.2.10 on 2020-07-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0027_auto_20200711_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='mycode', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshop.Coupon'),
            preserve_default=False,
        ),
    ]
