# Generated by Django 2.2.10 on 2020-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0028_auto_20200712_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
