# Generated by Django 2.2.10 on 2020-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0033_auto_20200712_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
    ]
