# Generated by Django 2.2.10 on 2020-07-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0034_auto_20200712_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshop.Coupon'),
            preserve_default=False,
        ),
    ]
