# Generated by Django 2.2.10 on 2020-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0035_auto_20200713_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='price',
            field=models.FloatField(default='2'),
            preserve_default=False,
        ),
    ]
