# Generated by Django 2.2.10 on 2020-07-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0036_bookstore_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(),
        ),
    ]
