# Generated by Django 2.2.10 on 2020-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0037_auto_20200713_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='discount_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
