# Generated by Django 2.2.10 on 2020-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0039_auto_20200713_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
