# Generated by Django 2.2.10 on 2020-07-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0040_auto_20200718_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='received',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_requested',
        ),
        migrations.AddField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshop.BillingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
