# Generated by Django 2.2.10 on 2020-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0041_auto_20200718_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referance_code',
            field=models.CharField(default='123', max_length=15),
            preserve_default=False,
        ),
    ]
