# Generated by Django 2.1 on 2020-07-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0049_auto_20200727_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
